In [61]:
import pandas as pd

Cargar el fichero

In [62]:
datos = pd.read_csv('../dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv')
datos.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

Comprobamos que el los datos que cargamos no hay NaN

In [63]:
datos.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Comprobar elementos duplicados

In [64]:
datos.duplicated().sum()

0

Comprobar que customerID no tenga duplicados

In [65]:
datos['customerID'].duplicated().sum()

0

Estandarizar formato

Mirar los tipos de datos de cada columna

In [66]:
datos.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

Transformar los tipos de datos que sean necesarios

In [67]:
# convertir a numerico en la tabla y guardamos en una variable  
total_charges = pd.to_numeric(datos.TotalCharges, errors='coerce')
datos.TotalCharges = pd.to_numeric(datos.TotalCharges, errors='coerce')

# los valores vacios los rellenamos con 0
datos.TotalCharges = datos.TotalCharges.fillna(0)

# mostramos los datos que antes de rellenar estaban vacios
datos[total_charges.isnull()][['customerID', 'TotalCharges']]

      customerID  TotalCharges
488   4472-LVYGI           0.0
753   3115-CZMZD           0.0
936   5709-LVOEQ           0.0
1082  4367-NUYAO           0.0
1340  1371-DWPAZ           0.0
3331  7644-OMVMY           0.0
3826  3213-VVOLG           0.0
4380  2520-SGTTA           0.0
5218  2923-ARZLG           0.0
6670  4075-WKNIU           0.0
6754  2775-SEFEE           0.0

Pasar todo a minuscula y poner _ en vez de espacios y -

In [68]:
# Funcion que remplaza los espacios por _ y pasa todo a minuscula 
replacer = lambda str: str.lower().str.replace(' ','_').str.replace('-','_')

# transformamos los indices de la tabla y los pasamos a minuscula 
# (con .str se accede a los valores de la serie)
datos.columns = replacer(datos.columns.str)
datos.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,No,No,Yes,No,Yes

In [69]:
# bucle que recorre todas las columnas cuyo tipo de dato sea objeto
for col in list(datos.dtypes[datos.dtypes == 'object'].index):
    # transformamos los datos dentro de la columna o fila 
    # de modo que quede en minuscula y con _ si hay separacion
    datos[col] = replacer(datos[col].str)
datos.head().T

,0,1,2,3,4
customerid,7590_vhveg,5575_gnvde,3668_qpybk,7795_cfocw,9237_hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month_to_month,one_year,month_to_month,one_year,month_to_month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

Pasar las columnas de dos valores, a 0 y 1

In [70]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod']
numerical = ['tenure', 'monthlycharges', 'totalcharges']
datos[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [71]:
datos.gender = (datos.gender == 'male').astype(int)
datos.partner = (datos.partner == 'yes').astype(int)
datos.dependents = (datos.dependents == 'yes').astype(int)
datos.phoneservice = (datos.phoneservice == 'yes').astype(int)
datos.paperlessbilling = (datos.paperlessbilling == 'yes').astype(int)
datos.churn = (datos.churn == 'yes').astype(int)

datos.head().T

,0,1,2,3,4
customerid,7590_vhveg,5575_gnvde,3668_qpybk,7795_cfocw,9237_hqitu
gender,0,1,1,1,0
seniorcitizen,0,0,0,0,0
partner,1,0,0,0,0
dependents,0,0,0,0,0
tenure,1,34,2,45,2
phoneservice,0,1,1,0,1
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month_to_month,one_year,month_to_month,one_year,month_to_month
paperlessbilling,1,0,1,0,1
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,0,0,1,0,1

Guardar

In [72]:
datos.to_csv('limpiezaDeDatosRuben.csv')